### ISSUE TITLE
Unable to retrieve image

### ISSUE THREAD

**Issue by aleonnet** [adlerweb/PdfQRSplit#3]
Hi @adlerweb how are you?
Great job! I could not use it due to the following error:
 ...
  File "PdfQRSplit.py", line 83, in split_qr
    img = Image.open(io.BytesIO(data))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x10a7f3450>

I'm using pillow 8.0.0 on a mac os 10.15.6, but already tried with older versions of pillow.

Please help me.

Regards,
Alessandro

**Comment by adlerweb** [comment]
As this issue is rather old and not reproducible for me, I assume it is no longer relevant and close it for now. If you – or someone else – encounters a similar problem, just comment here and provide a sample file, I'll reopen if it doesn't automatically.

**Comment by michawb** [comment]
Hallo Florian,

ich habe aktuell den selben Fehler:

`Processing file ../test.pdf.pdf containing 7 pages
  Analyzing page 1
    Writing page images to temporary directory /tmp/tmpzcsb3z9g
      Wrote image /tmp/tmpzcsb3z9g/I1.png; Checking for separator barcode
Traceback (most recent call last):
  File "/home/micha/qrcode/PdfQRSplit/PdfQRSplit.py", line 147, in <module>
    ofiles += splitter.split_qr(args.separator, ifiles)
  File "/home/micha/qrcode/PdfQRSplit/PdfQRSplit.py", line 81, in split_qr
    img = Image.open(io.BytesIO(data))
  File "/home/micha/miniconda3/lib/python3.10/site-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd33917c5e0>`

Die PDF kann ich leider aktuell so nicht zur Verfügung stellen, da dort Kundendaten vorhanden sind.
Ich schaue aber mal, ob ich ggf. eine Test machen kann ohne und würde mich dazu nochmal melden.

//Edit

Ich habe jetzt mal ein gescanntes Dokument als Test genommen und bekomme dabei folgenden Fehler:

`Processing file test2.pdf containing 7 pages
  Analyzing page 1
Traceback (most recent call last):
  File "/home/micha/qrcode/PdfQRSplit/PdfQRSplit.py", line 147, in <module>
    ofiles += splitter.split_qr(args.separator, ifiles)
  File "/home/micha/qrcode/PdfQRSplit/PdfQRSplit.py", line 75, in split_qr
    data = xObject[obj].getData()
  File "/home/micha/miniconda3/lib/python3.10/site-packages/PyPDF4/generic.py", line 843, in getData
    decoded._data = filters.decodeStreamData(self)
  File "/home/micha/miniconda3/lib/python3.10/site-packages/PyPDF4/filters.py", line 414, in decodeStreamData
    data = CCITTFaxDecode.decode(data, stream.get("/DecodeParms"), height)
  File "/home/micha/miniconda3/lib/python3.10/site-packages/PyPDF4/filters.py", line 361, in decode
    if decodeParms.get("/K", 1) == -1:
AttributeError: 'ArrayObject' object has no attribute 'get'`
