### ISSUE TITLE
Unsupported Filter /JBIG2Decode

### ISSUE THREAD

**Issue by FrittenIngenieur** [adlerweb/PdfQRSplit#4]
Hallo,
eigentlich ist dieses Script genau das was ich brauche. Allerdings bekomme ich immer den Fehler:

Processing file .\Test3.pdf containing 34 pages
  Analyzing page 1
Traceback (most recent call last):
  File "C:\Users\Micha\Downloads\PdfQRSplit-master\PdfQRSplit.py", line 154, in <module>
    ofiles += splitter.split_qr(args.separator, ifiles)
  File "C:\Users\Micha\Downloads\PdfQRSplit-master\PdfQRSplit.py", line 74, in split_qr
    data = xObject[obj].getData()
  File "C:\Python310\lib\site-packages\PyPDF4\generic.py", line 843, in getData
    decoded._data = filters.decodeStreamData(self)
  File "C:\Python310\lib\site-packages\PyPDF4\filters.py", line 423, in decodeStreamData
    raise NotImplementedError("unsupported filter %s" % filterType)
NotImplementedError: unsupported filter /JBIG2Decode

Ich habe vermutet, dass es an dem PDF-Dokument liegt. Leider finde ich keine Möglichkeit diesen Fehler zu umgehen.

Hat vielleicht jemand eine Idee?

**Comment by adlerweb** [comment]
Richtig, das Dokument ist in JBIG2 komprimiert. Das Format ist eher ungewöhnlich und wird gerne gemieden, da es z.B. zu vertauschten Zahlen in Dokumenten führen kann. Leider unterstützt PyPDF JBIG2 bisher nicht: https://github.com/py-pdf/pypdf/issues/951

Als Workaround könnte man die PDF-Datei vorher umwandeln. Hier z.B. mittels [Ghostscript](https://ghostscript.com/releases/gsdnld.html):
`gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf input.pdf`
Möglicher Haken: Ich bin mir nicht sicher, ob bei PDF-Dateien mit Text der erhalten bleibt oder in ein Bild umgewandelt werden.
